[package]
name = "clix"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["cargo", "string"] }
log = "0.4.22"
log4rs = "1.3.0"
serde = "1.0.204"
toml = "0.8.14"
